### ISSUE TITLE
celapi: Error 403

### ISSUE THREAD

**Issue by giacomofabbri** [indreias/abxba#2]
Hi since some days I get the Error 403 even changing the API code, would you mind help us? Thanks

**Comment by indreias** [comment]
Hello Giacomo,

Thank you for your report.

I'll check the problem and come back with my findings.

BR,
Ioan

**Comment by indreias** [comment]
Hello again,

It seems that starting from 2022-03-01 13:10:01 UTC the User Agent used by celapi project was blacklisted so I've updated to a more generic one and this seems to fix the issue.

Could you please confirm that all is fine from your side?

BR,
Ioan

**Comment by giacomofabbri** [comment]
Now it works perfectly! Thanks man
